-- CREATING DATA BASE 'DataWarehouse'--
/* THIS SCRIPT IS USED TO CREATE THE NEW DATA BASE AFTER CHECKING IF IT ALREADY EXISTS IF YES
IT WILL DELETE THE ENTIRE DATABASE AND RECREATE IT AND IT ALSO CREATE SCHEMAS WITHIN DATABASE 

**WARNING RUNNING THIS SCRIPT WILL DROP THE ENTIRE DATABASE** 
DO not run it if already exists
*/ 

	USE master;
	GO

	IF EXISTS(SELECT 1 FROM sys.databases WHERE name ='DataWarehouse')
	BEGIN
		ALTER DATABASE DataWarehouse SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
		DROP DATABASE DataWarehouse;
	END;
	GO

	CREATE DATABASE DataWarehouse;
	GO
	USE DataWarehouse;
	GO
	CREATE SCHEMA bronze;
	GO
	CREATE SCHEMA silver;
	GO
	CREATE SCHEMA gold;
	GO




